### ISSUE TITLE
FileField

### ISSUE THREAD

**Issue by br0th3r** [jrief/django-angular#107]
How to manage validation on client side for FileField? When I select a file, the field stays invalid and so the form.

**Comment by adrienbrunet** [comment]
Sum up:
Add `enctype="multipart/form-data"` to your `<form >` element
Some directives exist to have fancier rendering (like the one indicated above by @papasax).

PR #277 removes the border around the upload input. (it removes the class `form-control` on the input element)

**Comment by jrief** [comment]
django-angular's ``FileField`` and ``ImageField`` will offer full upload support in version 1.1.

Please help me to test this branch: https://github.com/jrief/django-angular/tree/features/upload-image

Those two fields also offer a much better UX than Django's own file fields. They work with both, Django-1.10 and Django-1.11
