### ISSUE TITLE
Namespace conflict with djangular

### ISSUE THREAD

**Issue by fladi** [jrief/django-angular#11]
There is another module which uses the same package namespace `djangular`:
https://github.com/appliedsec/djangular

This is rather unpleasant as it disallows to install both packages at the same time.

**Comment by AncientSwordRage** [comment]
This feature in Django 1.7 should help resolve this without renaming anything:  
https://docs.djangoproject.com/en/1.7/ref/applications/#configuring-applications  

The one thing I use djangular for is getting access to the settings variables (so I can point angular at the right urls etc).

That being said, #35 is *all about* renaming...so....is not renaming still an issue?
