### ISSUE TITLE
ModelFormSetView from contrib Django Extra Views and djangular

### ISSUE THREAD

**Issue by papasax** [jrief/django-angular#115]
Hi Jacob,

Have you tried to use formsets with django-angular?

I used the ModelFormSetView from the contrib Django Extra Views, It might be the reason of the error.

I tried to use ModelFormSetView to display multiple NgForm.... It looks like it kind of works, except the errors are rendered like this
```html
<li>(u'basket_form.form-0.image', u'djng-form-control-feedback djng-field-errors', u'$dirty', u'$error.required', u'invalid', u'Ce champ est obligatoire.')</li>
```
this comes from the "_html_output" method of the form base class.
Usually the bf_error is a class 'djangular.forms.angular_base.TupleErrorList'
Here it is a class 'django.forms.utils.ErrorList'

I guess this is the reason.... 
Can you tell me how to use FormSet with djangular? Maybe a formset mixin....

This is what I did:
```python
class LivreModelForm(NgModelFormMixin, NgFormValidationMixin, Bootstrap3FormMixin, forms.ModelForm):
    form_name = 'basket_form'
    scope_prefix = 'basket_data'
    class Meta:
    model = Livre
```
I created a function as_div
```python
def as_div(self):
    forms = ' '.join(form.as_div() for form in self)
    return mark_safe('\n'.join([six.text_type(self.management_form), forms]))
```
that I added to my formset within my ModelFormSetView
```python
class LivrePanierFormSet(ModelFormSetView):
    template_name = 'tmpl/basket_detail.html'
    model = Livre
    form_class = LivreModelForm
   
    def get_form_class(self):
        return self.form_class

    def get_formset(self):
        """
        Returns the formset class from the model formset factory
        """
        formset = super(LivrePanierFormSet, self).get_formset()
        formset.form_name = self.form_class.form_name
        formset.as_div = as_div
        return formset
```

**Comment by adrienbrunet** [comment]
A few months passed.. Have you found a solution for that? Is taht still a issue? In your model, you shouldn't use forms.ModelForm in addition to NgModelFormMixin, right? I may try formset with django-angular in the next days..

**Comment by papasax** [comment]
No finally i did not use formsets. I had basic needs, and I used a ng-repeat directly in angular. I would be interested to see if you manage to do it.

**Comment by jrief** [comment]
Sorry for not helping here, but currently I have no resources to add this feature to the project, because I am involved into another project.
Please try to implement it yourself or sponsor this feature.

**Comment by adrienbrunet** [comment]
Well, my planning changed and the previous feature does not require anymore formset... :cry: If I find some time to implement it, I'll try...

**Comment by adrienbrunet** [comment]
Formset are still not that well supported and documented but we have several issues about it. Closing this one.
