### ISSUE TITLE
djangoRMIProvider + FORCE_SCRIPT_NAME

### ISSUE THREAD

**Issue by pitervergara** [jrief/django-angular#121]
I'm trying to use remote method invocation. In the template I have the following:

``` javascript
my_app.config(function(djangoRMIProvider) {
    djangoRMIProvider.configure({% djng_current_rmi %})
});
```

I have FORCE_SCRIPT_NAME = "/app16" defined in my settings.py (https://docs.djangoproject.com/en/1.6/ref/settings/#force-script-name), but when the page is rendered, the resulting path does not include the FORCE_SCRIPT_NAME portion of the URL.

Considering my view, the current result is:

``` javascript
{
    "get_servicos":{
        "url":"/cartaocorreio/prestcontas/criar",
        "headers":{
            "DjNg-Remote-Method":"get_servicos"
        },
        "method":"auto"
    }
}
```

but the expected result is:

``` javascript
{
    "get_servicos":{
        "url":/app16/cartaocorreio/prestcontas/criar",
```

Can someone provide me some guidance on how to solve this issue?

-- Edit:
Using: django-angular 0.7.9 and Django 1.6

**Comment by adrienbrunet** [comment]
@pitervergara Django 1.6 is not supported anymore. Have you fixed your problem?
Closing this for now. (2 years inactivity)
