### ISSUE TITLE
Append an asterisk in the label for the required fields

### ISSUE THREAD

**Issue by grouser** [jrief/django-angular#129]
At this moment the user can't know if a field is required or not.

**Comment by aronysidoro** [comment]
Jrief,

First I just want to thank you for this amazing library.  It has really helped speed up development for easy client-side validation with Django forms!

Now, for my question ;)

I tried this to add a red asterisk, by adding this to my CSS:

```
input[required="required"]::after {
    content: "*";
    color: red;
    ...
}
```

But the `Bootstrap3ModelForm` doesn't show `required` in the DOM, so it didn't work.  

Am I missing something?

Are there any other solutions?

**Comment by adrienbrunet** [comment]
Have you provided the required_css_class attribute on your form?

**Comment by aronysidoro** [comment]
@adrienbrunet you are exactly correct. Thank you for your help!

I got this to work by adding this to my *Django Form*:

```python
required_css_class = 'required'
```

And, used this *CSS*:

```css
label.required::after {
    content: "*";
    color: red;
}
```

**Comment by adrienbrunet** [comment]
:+1: 

@jrief I think it will be better to add this clearly in the docs so that we can close this issue.

**Comment by adrienbrunet** [comment]
@aronysidoro I updated the docs so I'm closing this issue. Thank you very much for your contribution. Any input is really appreciated =)
