### ISSUE TITLE
Widget forms.CheckboxSelectMultiple selects all the boxes.

### ISSUE THREAD

**Issue by grouser** [jrief/django-angular#131]
I have a form defined like that:

class ProductForm(NgFormValidationMixin, NgModelFormMixin, Bootstrap3ModelForm):
     purses = forms.ModelMultipleChoiceField( 
         queryset=Purse.objects.all(), 
         widget=forms.CheckboxSelectMultiple)
    .........

If a select any checkbox, the other ones are automatically selected as well.

**Comment by adrienbrunet** [comment]
I think I missed something, I still have the following problem:
"If a select any checkbox, the other ones are automatically selected as well." running django-angular 0.7.10

I have a Model with a m2m relation:

    class Thing(models.Model):
        pass
    
    class SomeStuff(models.Model):
         things = models.ManyToManyField(Thing)


    class MyForm(NgModelFormMixin, NgFormValidationMixin, Bootstrap3ModelForm):
        scope_prefix = 'foo'
        form_name = 'foo_form'
    
        class Meta:
            model = SomeStuff
            fields = ('things', )
            widgets = {'things': forms.CheckboxSelectMultiple()}


Also, the html rendering is wrong, I have the same layout than @grouser (did you fix it somehow?)

**Comment by jrief** [comment]
The "Angular part" of this project changed quite a lot since 0.7.10. This fixed some issues with multiple checkboxes.

**Comment by adrienbrunet** [comment]
But the latest available (stable) release is 0.7.10 right? Any release date to expect soon?

**Comment by jrief** [comment]
Sorry, forgot to update the news section.
Thanks for reporting.

**Comment by adrienbrunet** [comment]
:trophy: :smile: You made my day with that release I wasn't aware of.

**Comment by adrienbrunet** [comment]
Hey, after the update... I still have the same issue. If a multipleChoiceField renders perfectly, the ModelMultipleChoiceField still has the same issue than before.
Another question, can we defined somehow a way to bind the ModelMultipleChoiceField with its queryset dynamically? For a select Field, we can define `self.field['my_field'].widget.attrs['ng-option'] = ..`

**Comment by lobomacz** [comment]
Hi, I have a similar issue with the ChoiceField. I define the following form:

class FormReservacion(NgModelFormMixin,NgFormValidationMixin,Bootstrap3Form):
	scope_prefix ='reservacion_data'
	form_name = "form_reservacion"
	OPCIONES = models.PAQUETE.objects.values_list('id','titulo')
	idcliente = forms.CharField(label='Id de Cliente',required=True)
	paquete = forms.ChoiceField(choices=OPCIONES,label='Paquete Turístico',empty_label='--Seleccione--',required=True)
	fecha_res = forms.DateField(label='Fecha de Reservacion',widget=forms.widgets.DateInput(attrs={'validate-date':'^(\d{4})-(\d{1,2})-(\d{1,2})$'}),required=True)
	cantidad_pers = forms.IntegerField(label='Cantidad de Personas',required=True)
	class Meta:
		fields = '__all__'

and when I try to run the server I get an error message like this:

class ChoiceFieldRenderer(widgets.ChoiceFieldRenderer):
AttributeError: 'module' object has no attribute 'ChoiceFieldRenderer'

What could possibly be the problem?
