### ISSUE TITLE
Validation errors doesn't show on Django 1.7.4 and AngularJS 1.3.13

### ISSUE THREAD

**Issue by FabrizioA** [jrief/django-angular#142]
Hi,

I'm trying to implement django-angular inside my Django admin application.

<strong>admin_views.py</strong>
```python
class ContractAdminView(FormView):
    template_name = "admin/django_car_rental/contract/change_form.html"
    form_class = ContractAdminForm
```

<strong>forms.py</strong>
```python
from djangular.forms import NgModelForm, NgModelFormMixin, NgFormValidationMixin, NgForm
from models import Contract

class ContractAdminForm(NgFormValidationMixin, NgModelFormMixin, NgModelForm):

    class Meta:
        model = Contract

    class Media:
        js = ('admin/js/angular.min.js', 'djangular/js/django-angular.min.js', 'admin/js/contract_change_form.js')
        css = {'all': ('djangular/css/styles.css',)}
```

<strong>my_script.js</strong>
```javascript
var contract_form_app = angular.module('ContractFormApp', ['ng.django.forms']);

contract_form_app.config(function($httpProvider, $interpolateProvider) {
    $httpProvider.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
    $interpolateProvider.startSymbol('{$');
    $interpolateProvider.endSymbol('$}');
});

/* Controllers */
contract_form_app.controller("mainCtrl", ['$scope', function($scope) {

}]);
```

<strong>change_form.html</strong>
```html
{% extends "admin/base_site.html" %}
{% block title %}
    New Contract
{% endblock %}
{% block extrahead %}
    {{ form.media }}
{% endblock %}
{% block content %}
        <div ng-app="ContractFormApp">
            <form ng-controller="mainCtrl" name="contract_form" method="post" action="">
                {% csrf_token %}
                {{ form }}
                <button type="submit">Save</button>
            </form>
       </div>
{% endblock %}
```

When I submit the form only the border field is red and no any other messages will display.
Here the rendered template of a field section.

```html
<ul class="djng-field-errors ng-hide" ng-show="Q29udHJhY3RBZG1pbkZvcm0.date.$dirty"><li ng-show="Q29udHJhY3RBZG1pbkZvcm0.date.$error.required" class="invalid ng-hide">Questo campo è obbligatorio.</li><li ng-show="Q29udHJhY3RBZG1pbkZvcm0.date.$valid" class="valid ng-hide"></li></ul>
<ul class="djng-field-errors ng-hide" ng-show="Q29udHJhY3RBZG1pbkZvcm0.date.$pristine"><li ng-show="Q29udHJhY3RBZG1pbkZvcm0.date.$pristine" class="invalid ng-hide">Questo campo è obbligatorio.</li><li ng-show="Q29udHJhY3RBZG1pbkZvcm0.date.$message" class="invalid ng-binding ng-hide" ng-bind="Q29udHJhY3RBZG1pbkZvcm0.date.$message"></li></ul>
<input djng-error="bound-field" id="id_date" name="date" ng-model="date" ng-required="true" type="text" class="ng-pristine ng-invalid ng-invalid-bound ng-invalid-required ng-touched" required="required">
```

Is this a bug or I'm using django-angular in wrong way?

**Comment by jrief** [comment]
You can't do that.
If you want to create an alternative form for your Django admin, either specify it in your own ``ModelAdmin`` with ``form = ...``, or override the method ``get_form()``.

**Comment by FabrizioA** [comment]
I've already override add_view() of ModelAdmin to return ContractAdminView.as_view()(requests).
My problem isn't solved yet :(
Do you say that I can't use django-angular form inside Django Admin?

**Comment by jrief** [comment]
> Do you say that I can't use django-angular form inside Django Admin?

No, I'm saying, that you have to construct your forms inside the Django admin, the way intended. Override ``get_form()`` and return a form you have built there.

**Comment by FabrizioA** [comment]
Thanks for reply jrief but I don't understand the difference between passing my form tu get_form() and pass it with my ContractAdminView.
When I submit the form, the errors of validation  doesn't show.... (See results template above), that' si my problem. Sorry for my basic questions... :(

**Comment by FabrizioA** [comment]
I'm sorry jrief for my question and this post issue...
I've read the whole documentation again and I was able to implement django-angular inside my django admin application.

I have only the last two questions:
1) How can I set IT Date format DD-MM-YYYY field validation? I've edited the validate-date attribute but it doesn't works.
2) As you can see, I have a NGModelForm with the Meta.model = Contract. If I remove my date form.DateField then the form validation doesn't works... Why I need to specify all my model fields if I use a ModelForm?

```python
class ContractAdminForm(NgModelFormMixin, NgFormValidationMixin, NgModelForm):
    form_name = "contract_form"
    scope_prefix = 'subscribe_data'

    date = forms.DateField(label='Date of birth',
        widget=forms.DateInput(attrs={'validate-date': '^(\d{1,2})/(\d{1,2})/(\d{4})$', 'v-date-field': ''}),
        help_text='Allowed date format: dd-mm-yyyy')

    class Meta:
        model = Contract
        fields = '__all__'
```

Thanks for your help and patience.

**Comment by jrief** [comment]
how does your model ``Contract`` look like?

**Comment by FabrizioA** [comment]
Actually my model Contract is:

```python
class Contract(models.Model):
    date = models.DateTimeField(null=False, blank=False, verbose_name="Data contratto")
    time = models.TimeField(null=False, blank=False, verbose_name="Ora contratto")
    # Checkout info.
    checkout_place = models.ForeignKey(CheckOutPlace, null=False, blank=False, verbose_name="Luogo consegna",
                                       related_name="checkout_place_contracts")
    checkout_date = models.DateTimeField(null=False, blank=False, verbose_name="Data consegna")
    checkout_time = models.TimeField(null=False, blank=False, verbose_name="Ora consegna")
    # Expected checkin info.
    expected_checkin_place = models.ForeignKey(CheckOutPlace, null=False, blank=False, verbose_name="Luogo rientro "
                                                                                                    "previsto",
                                               related_name="expected_checkin_place_contracts")
    expected_checkin_date = models.DateTimeField(null=False, blank=False, verbose_name="Data rientro prevista")
    # Vehicle
    vehicle = models.ForeignKey(Vehicle, null=False, blank=False, verbose_name="Veicolo")
    # Customer
    customer = models.ForeignKey(Customer, null=False, blank=False, verbose_name="Intestatario contratto")

    def __unicode__(self):
        return unicode(self.date) + " " + self.vehicle.name

    class Meta:
        verbose_name = "Contratto"
        verbose_name_plural = "Contratti"
```

It will have a lot of others fields...

**Comment by jrief** [comment]
Have you followed the Django guide on overriding model form fields?
https://docs.djangoproject.com/en/1.7/topics/forms/modelforms/#overriding-the-default-fields

**Comment by FabrizioA** [comment]
Thanks, I've read the docs and I figured out why I need to specify form fields inside my model form.
Now, I can't realize how can I solve the dd/mm/yyyy date validation...
[Here my rendered page] (https://www.dropbox.com/s/9r2logodtjn24zu/Schermata%202015-02-14%20alle%2015.59.44.png?dl=0)

here full forms.py (you can notice the inclusione of 'admin/js/angular-locale_it-it.js',)
```python
from models import Contract
from djangular.forms import NgModelFormMixin, NgFormValidationMixin, NgModelForm
from django import forms

class ContractAdminForm(NgModelFormMixin, NgFormValidationMixin, NgModelForm):
    form_name = "contract_form"
    scope_prefix = 'subscribe_data'

    date = forms.DateField(label='Date of birth',
        widget=forms.DateInput(attrs={'validate-date': '^(\d{1,2})/(\d{1,2})/(\d{4})$', 'v-date-field': ''}),
        help_text='Allowed date format: dd-mm-yyyy')

    class Meta:
        model = Contract
        fields = '__all__'

    class Media:
        js = ('admin/js/core.js',
              'admin/js/admin/RelatedObjectLookups.js',
              'admin/js/jquery.js',
              'admin/js/jquery.init.js',
              'admin/js/actions.js',
              'admin/js/calendar.js',
              'admin/js/DateTimeShortcuts.js',
              'admin/js/angular.min.js',
              'admin/js/angular-locale_it-it.js',
              'djangular/js/django-angular.min.js',
              'admin/js/ng-django-forms.js',
              'admin/js/contract_change_form.js',
              'admin/js/contract_change_form_directives.js',
              )
        css = {'all': ('admin/css/forms.css', 'admin/css/widgets.css', 'admin/css/djangular_styles.css')}
```

my contract_change_form.js (Where I have declared the AngularJS app). You can notice the inclusion of  "ngLocale" dependency.
```javascript
/**
 * Created by Fabrizio Alongi 10/02/15.
 */
var contract_form_app = angular.module('ContractFormApp', ['ng.django.forms', "ngLocale"]);

contract_form_app.config(function($httpProvider, $interpolateProvider) {
    $httpProvider.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
    $interpolateProvider.startSymbol('{$');
    $interpolateProvider.endSymbol('$}');
});

/* Controllers */
contract_form_app.controller("mainCtrl", ['$scope', '$http', '$location', function($scope, $http, $location) {
    
}]);
```

**Comment by jrief** [comment]
What is this ``v-date-field`` for?

**Comment by FabrizioA** [comment]
vDateField is my custom directive to add the support to default date widget of django admin.
Since that date picker is developed in plan javascript, I had the need to trigger a 'change' event to my input field and the listen to this event to update the ng-model variable.

```javascript
contract_form_app.directive('vDateField', [function() {
    return {
        require: "ngModel",
        restrict: "A",
        link: function(scope, element, attrs, ngModelCtrl) {
            element.addClass("vDateField");
            var updateModel = function (dateText) {
                scope.$apply(function () {
                    ngModelCtrl.$setViewValue(dateText);
                });
            };
            django.jQuery('input').on('change', function() {
                updateModel(element.val());
            });
        }
    };
}]);
```

**Comment by jrief** [comment]
You should not mix jQuery and AngularJS.
Why don't you try with http://angular-ui.github.io/bootstrap/#/datepicker
this is written in pure AngularJS.

**Comment by FabrizioA** [comment]
I've seen it .... at this time I've chosen the default date widget of django because I use it in any other form of my application (pages that doesn't has complex user interactions).

If can I ask you an advice, I need to develop a car rental booking system, I've implemented many Cars, Tariffs,... registers with plain django admin, but now, I need to developer the page for create a Contract. This page/form will contain many fields. On problem I need to solved is: when a user select one car from < select ... > field, I need to show up a related informations of this car in a separate < div >. Another "problems" may be, when the user select a category car (from a < select .. > field) I need to populated the <select ... > of available tariffs of this category.
How you can notice, there is a lot of interaction between user and page, and, page and server.
For me it hard too choose between a pure angularjs page (without django forms {{ form }} ) and REST architecture and a page with django-angular and all django forms functionalities.
If I develop a page that relies on a classic django forms validation (with classic post back) and angularjs... I need to restore the entire state of angularjs at each page refresh, but, I have client validation for free. [Here one problem I had to main a state of a select element with angularjs] (http://stackoverflow.com/questions/28504620/save-ng-options-selected-state-after-form-post)

Can you give me your opinion about it?
It's important for me, I will appreciate it very. 
Thanks for your Saturday afternoon time.

[Here can you find a draft of a page I need to create] (https://www.dropbox.com/s/b1138e1zvdzxqwi/IMG_0365.jpg?dl=0).
