### ISSUE TITLE
Django 1.8 beta 2

### ISSUE THREAD

**Issue by papasax** [jrief/django-angular#154]
Hi,

I just wanted to test the library with the new Django 1.8 beta 2.
I get this error on form rendering:

'''
  File "/Users/Exlivris3/.virtualenvs/bibliocratie/lib/python2.7/site-packages/django/forms/forms.py", line 202, in _html_output
    top_errors = self.non_field_errors()  # Errors that should be displayed above all fields.
  File "/Users/Exlivris3/.virtualenvs/bibliocratie/lib/python2.7/site-packages/djangular/forms/angular_model.py", line 68, in non_field_errors
    errors = super(NgModelFormMixin, self).non_field_errors()
  File "/Users/Exlivris3/.virtualenvs/bibliocratie/lib/python2.7/site-packages/djangular/forms/angular_base.py", line 256, in non_field_errors
    errors = super(NgFormBaseMixin, self).non_field_errors()
  File "/Users/Exlivris3/.virtualenvs/bibliocratie/lib/python2.7/site-packages/django/forms/forms.py", line 309, in non_field_errors
    return self.errors.get(NON_FIELD_ERRORS, self.error_class(error_class='nonfield'))
TypeError: __init__() got an unexpected keyword argument 'error_class'
'''

**Comment by jrief** [comment]
Thanks for reporting.
This is really important and we have to keep it open until fixed.
Unfortunately I had to jump deeply into Django's Form framework to add all the required features.

**Comment by woostersoz** [comment]
Hi - just wanted to check if you had an ETA on this fix? It's preventing me from using Django 1.8 which I need for other parts. Thanks

**Comment by jrief** [comment]
Sorry, no time for this yet.
In my current project I'm still stuck on Django-1.6 because of a issue 51 in django-parler.
Any patches are welcomed.

**Comment by AntonOfTheWoods** [comment]
Hi,

As Django 1.8 is now in PyPi, trying out your examples now no longer works - the requirements files simply specifies django>=1.6 and 1.8 is the default and doesn't work. I'll have a look but am still a noob so can't promise anything...

**Comment by Nekmo** [comment]
We have the same problem here. In our project we are using Django 1.8 and can not downgrade by this module.

Please, comment when this is fixed.

Thank you very much.

**Comment by jrief** [comment]
@Nekmo did PR #164 fix this? If so, please inform me, I then would release a new version to PyPI.

**Comment by iynaix** [comment]
It seems to have fixed the issue for me.

**Comment by jrief** [comment]
and @Nekmo did it fix your problem too?

**Comment by Nekmo** [comment]
I'll try later when I am in the office. Thanks :)

**Comment by papasax** [comment]
I did try on my project with Django 1.8.1. It seems to work fine.

2015-05-07 10:24 GMT+02:00 Nekmo <notifications@github.com>:

**Comment by Nekmo** [comment]
@jrief This works for me, thanks :D please, upload new version to Pypi.

**Comment by jrief** [comment]
@Nekmo 
If django-angular version 0.7.14 fixes this issue, please close.
