### ISSUE TITLE
 ImportError: Module "djangular.middleware.DjangularUrlMiddleware" does not define a "DjangularUrlMiddleware" attribute/class

### ISSUE THREAD

**Issue by gabn88** [jrief/django-angular#162]
When I upgraded my production server to use django-angular it gave me the following error and a 500 internal server error:

 ImportError: Module "djangular.middleware.DjangularUrlMiddleware" does not define a "DjangularUrlMiddleware" attribute/class

I have installed djangular using pip install --user django-angular.

On my test server the same settings do work (there django-angular is installed in the virtual environment using pip install django-angular). Does anybody know how I can fix this?

The strange thing is that python2.7 manage.py check does not give any errors on my production server...

**Comment by jkosir** [comment]
Strange. Can you manually import ``DjangularUrlMiddleware``?

**Comment by gabn88** [comment]
It was indeed a strange problem.

STeps I did to resolve it (not sure which step fixed it):
1. pip uninstall django-angular
2. go to app directory explicitly and reinstall django-angular (pip install --user django-angular)
3. upgrade django from 1.7.3 to 1.7.7
4. stop, wait a few minutes, and start the server again.

Now it is working! So I guess the problem has nothing to do with django angular... Sorry!
