### ISSUE TITLE
scope_prefix shows other string

### ISSUE THREAD

**Issue by mateuo** [jrief/django-angular#163]
Hi, first of all sorry if this is not an issue, could be a bad use of your library on my side.

When I look into the rendered form's components the ng-model supposed to be 'scope_prefix.name_component' but is something like 'dmyxxxxxxxx.name_component' where x are numbers.

This is not a big issue because for form to form this ng-model is different so I can use it.
Thank you in advance
Your library is very useful indeed
These are my files:

forms.py
__author__ = 'mateu'
from django import forms
from djangular.forms import NgModelFormMixin, NgModelForm
from djangular.styling.bootstrap3.forms import Bootstrap3FormMixin
from extraescolares.models import Progenitor, Mail, Direccion

class ProgenitorForm(Bootstrap3FormMixin, forms.ModelForm):
    class Meta:
        model = Progenitor
        prefix = 'progenitor_form'
        fields = 'nom', 'llinatge1', 'llinatge2', 'telf', 'telf_mob', 'obs'

        def __init__(self, *args, **kwargs):
            kwargs.update(scope_prefix='progenitor')
            super(ProgenitorForm, self).__init__(*args, **kwargs)

class MailForm(Bootstrap3FormMixin, forms.ModelForm):
    class Meta:
        model = Mail
        prefix = 'mail_form'
        fields = 'nom',

        def __init__(self, *args, **kwargs):
            kwargs.update(scope_prefix='mail')
            super(MailForm, self).__init__(*args, **kwargs)

class DireccionForm(Bootstrap3FormMixin, forms.ModelForm):
    class Meta:
        model = Direccion
        prefix = 'direccion_form'
        fields = 'tipo_direccion', 'nombre_direccion', 'numero', 'piso', 'puerta', 'escalera', 'cp',\
                 'ciudad', 'estado', 'pais'

        def __init__(self, *args, **kwargs):
            kwargs.update(scope_prefix='direccion')
            super(DireccionForm, self).__init__(*args, **kwargs)

views.py
import json
from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView, CreateView, FormView
from .forms import ProgenitorForm, DireccionForm
from .models import Progenitor, Direccion
from django.utils.encoding import force_text

class WebView(TemplateView):
    template_name = 'index.html'

class DialogView(TemplateView):
    template_name = 'partials/dialog.html'

class AddressFormView(FormView):
    model = Direccion
    template_name = 'partials/address.html'
    form_class = DireccionForm
    success_url = reverse_lazy('form_data_valid')

    def get_context_data(self, **kwargs):
        context = super(AddressFormView, self).get_context_data(**kwargs)
        context.update(direccion_form=DireccionForm())
        return context

class View1(TemplateView):
    template_name = 'partials/view1.html'

class View2(TemplateView):
    template_name = 'partials/view2.html'

class ProgenitorFormView(FormView):
    model = Progenitor
    template_name = 'partials/progenitor.html'
    form_class = ProgenitorForm
    success_url = reverse_lazy('form_data_valid')

    def get_context_data(self, **kwargs):
        context = super(ProgenitorFormView, self).get_context_data(**kwargs)
        context.update(progenitor_form1=ProgenitorForm())
        context.update(progenitor_form2=ProgenitorForm())
        return context

    def post(self, request, **kwargs):
        if request.is_ajax():
            return self.ajax(request)
        return super(ProgenitorFormView, self).post(request, **kwargs)

    def ajax(self, request):
        form = self.form_class(data=json.loads(request.body))
        response_data = {'errors': form.errors, 'success_url': force_text(self.success_url)}
        return HttpResponse(json.dumps(response_data), content_type="application/json")

progenitor.html

<div class="well">
  <h3>Formulari per donar d'alta progenitors</h3>
  <form ng-controller="CtrlProgenitor" name="progenitor_form1" novalidate class="form-horizontal">
    <h4>Primer progenitor</h4>{{ progenitor_form1.as_div }}
    <div class="form-group"><a ng-click="openDialog(1)" id="address_progenitor1" class="btn btn-mini">Afegeix Adreça Progenitor 1</a></div>
    <div class="form-group">
      <label>Adreça introduida progenitor1</label>
    </div>
    <div class="form-group">
      <label>{$address_progenitor1$}</label>
    </div>
    <label>Familia Monoparental?
      <input type="checkbox" name="familia_monoparental" unchecked ng-model="monoparental">
    </label>
  </form>
  <div ng-show="!monoparental">
    <form ng-controller="CtrlProgenitor" name="progenitor_form2" novalidate class="form-horizontal">
      <h4>Segon progenitor</h4>{{ progenitor_form2.as_div }}
      <label>Mateixa adreça per els dos progenitors?
        <input type="checkbox" name="progenitors_mateixa_adreça" unchecked ng-model="junts">
      </label>
      <div ng-show="!junts"><a ng-click="openDialog(2)" id="address_progenitor2" class="btn btn-mini">Afegeix Adreça Progenitor 2</a>
        <label>Adreça introduida progenitor2</label>
        <label>{$address_progenitor2$}</label>
      </div>
    </form>
  </div>
  <div>
    <button type="button" ng-click="submit()" class="btn btn-primary">Desar</button>
  </div>
</div>

**Comment by jrief** [comment]
> When I look into the rendered form's components the ng-model supposed to be 'scope_prefix.name_component' but is something like 'dmyxxxxxxxx.name_component' where x are numbers.

This is explained by the documentation. The name of the scope **MUST** be different from the name of the form, so that form errors can be shown in its context. If you don't specify a name, djng invents one.

**Comment by mateuo** [comment]
Oh! what a shame, sorry.

Thank you for your answer
