### ISSUE TITLE
Weird behavior for checkbox

### ISSUE THREAD

**Issue by adrienbrunet** [jrief/django-angular#166]
Hi,

On the demo page, when I click on one of the choices of "Notify by", I get the "This field is required" error message.
The error message disappears if I click another checkbox, but then, if I unchecked one of the
 selected boxes, the message "This field is required" is not shown again. It's not really consistent.

Any idea?

**Comment by jrief** [comment]
@adrienbrunet Thanks for reporting!
On my last deployment, I forgot to invoke ``collectstatic``.
