### ISSUE TITLE
Angular binding and accent é è à ...

### ISSUE THREAD

**Issue by adrienbrunet** [jrief/django-angular#168]
Hi, I have a field with an "é" in its name. I get a parse:lexerr due to ng-model="myModel.myFieldWith_é". According to stackoverflow, calling the attribute that way:

    myModel['myFieldWith_é']

will solve the problem as this plunkr suggest : 

http://plnkr.co/edit/QNdSIxro2VxS131BMhm6?p=preview

In your code, it would mean change

    def get_widget_attrs(self, bound_field):
        attrs = super(NgModelFormMixin, self).get_widget_attrs(bound_field)
        identifier = self.add_prefix(bound_field.name)
        ng = {
            'name': bound_field.name,
            'identifier': identifier,
            'model': self.scope_prefix and ('%s.%s' % (self.scope_prefix, identifier)) or identifier
        }

and write something like "%s['%s']" % (self.scope_prefix, identifier) or identifier.

Is there any reason I'm missing why it should not be that way? 

With your approval, I can submit a PR if you don't have the time to edit it.

**Comment by jrief** [comment]
Well noticed. Thanks!
