### ISSUE TITLE
Is it possible to change the base url djangoUrl uses to lookup the reverse url?

### ISSUE THREAD

**Issue by gabn88** [jrief/django-angular#170]
I would like, for my app, to lookup the som urls on a different server, now it always does:

http://server2/djangular/url/?djng_url_name=etcetc..

But I would like to configure that it does:

http://server1/djangular/url/?djng_url_name=etcetc..

Is that possible?

**Comment by jkosir** [comment]
Currently discussing this in #169, something to make this possible will be implemented soon.
