### ISSUE TITLE
form_class attribute in NgCRUDView

### ISSUE THREAD

**Issue by adrienbrunet** [jrief/django-angular#173]
Yup,

could we add a form_class attribute to the NgCRUDView (like in regular FormView)? Right now, we can override `def get_form_class` but it would be easier that way. (And it's misleading without it)

I can make a PR if you don't have time for that

Cheers

**Comment by jrief** [comment]
@jkosir Since I do not have any experience with NgCRUDView, its up to you to decide.

**Comment by jkosir** [comment]
Huh yep, that makes sense. I'd appreciate a PR.

Thanks!
