### ISSUE TITLE
Does anybody has experience with AngularJS-1.3 ?

### ISSUE THREAD

**Issue by jrief** [jrief/django-angular#174]
Today I migrated a project to AngularJS-1.3.16. Except a few tweaks in other Angular modules this migration was quite smooth.
Whoever uses **django-angular** with AngularJS-1.3, please drop me a line.

**Comment by papasax** [comment]
I do. No problème.

**Comment by bafflermeal** [comment]
I haven't seen any problems using it with 1.3.16.

**Comment by adrienbrunet** [comment]
No problem so far.

**Comment by jrief** [comment]
Thanks for testing. I neither experienced any problems with AngularJS-1.3.
