### ISSUE TITLE
data binding with redis-py database?

### ISSUE THREAD

**Issue by mingissb** [jrief/django-angular#181]
Hello,
I have a project use redis-py as cache database.
coding example:
    #!/usr/bin/python2.7
    import redis
    redisconfig = {'host': 'localhost', 'port': 6379,'db': 0,}
    r = redis.StrictRedis(**redisconfig)

Is there a solution to databinding with the r ?
As I'm new to angular, I see how databinding with models.
But binding to redis no find.
Any body could help me ?
Or will django-angular do add some feature with redis in future?
Thanks in advance.

**Comment by jrief** [comment]
Currently that's out of scope for this project.
Please do not ask such generic questions, this forum is intended for reporting bugs and asking concrete questions about the documentation.
