### ISSUE TITLE
TypeError: djangoWebsocketProvider.prefix is not a function

### ISSUE THREAD

**Issue by valdemarrolfsen** [jrief/django-angular#189]
Hi,

I am trying to install three way data binding, but the system fails to instantiate the module due to the following error:

TypeError: djangoWebsocketProvider.prefix is not a function

My configuration code:

var main = angular.module('main', ['ngRoute', 'ngResource', 'ngAnimate',  'ngCookies','leaflet-directive', 'angularFileUpload', 'ng.django.websocket']);

//-------------------- Configuration --------------------

main.config(function($interpolateProvider) {
    $interpolateProvider.startSymbol('{$');
    $interpolateProvider.endSymbol('$}');
  });

main.config(function($httpProvider){
  $httpProvider.defaults.xsrfCookieName = 'csrftoken';
  $httpProvider.defaults.xsrfHeaderName = 'X-CSRFToken';
});

main.config(function(djangoWebsocketProvider) {
    // use '/ws' as the websocket's prefix
    djangoWebsocketProvider.prefix('/ws');

```
// optionally inform about the connection status in the browser's console
djangoWebsocketProvider.debug(true);
```

});

I chekced and the django-angular.min.js is imported.

Any ideas?

**Comment by jrief** [comment]
This sounds like a configuration error. Please use the demo project as a starting point. Then evolve your application from there.

**Comment by jrief** [comment]
Were you able to fix it?

**Comment by adrienbrunet** [comment]
I guess @valdemarrolfsen fixed his problem. If not, we can reopen the issue later on. But it is useless to let it open 6months after without feedback.

**Comment by prokoptsev** [comment]
I have same problem. Examples from [Three-way data-binding](https://github.com/jrief/django-angular/blob/0.8.1/docs/three-way-data-binding.rst) is wrong or deprecated.
Configuration should look like this:
```javascript
my_app.config(function(djangoWebsocketProvider) {
    // use '/ws' as the websocket's prefix
    djangoWebsocketProvider.setURI('{{ WEBSOCKET_URI }}');
    djangoWebsocketProvider.setHeartbeat({{ WS4REDIS_HEARTBEAT }});

    // optionally inform about the connection status in the browser's console
    djangoWebsocketProvider.setLogLevel("debug");
});
```
And `controller` like this:
```javascript
my_app.controller('MyController', function($scope, djangoWebsocket) {
    djangoWebsocket.connect($scope, 'my_collection', 'foobar', ['subscribe-broadcast', 'publish-broadcast']);

    // use $scope.my_collection as root object for the data which shall be three-way bound
});
```
where `foobar ` is name of facility and `['subscribe-broadcast', 'publish-broadcast']` is channels.
Please, actualize the documentation.

**Comment by jrief** [comment]
@valdemarrolfsen could you then please update the docs and create a pull request. The demo project uses working code.

**Comment by valdemarrolfsen** [comment]
Sorry for my incredible late reply... I actually went with another solution, so I never found the solution to this problem. Maybe @prokoptsev can do it?

**Comment by prokoptsev** [comment]
Sure!
#250
