### ISSUE TITLE
Angular bound form with ng-init

### ISSUE THREAD

**Issue by Bgeninatti** [jrief/django-angular#190]
Hi everybody. 
This is a really good library and very useful.
I was wondering if could use ng-init to make bound forms in angular, and avoid to use django-angular.js. May be overriding the widget for each form in NgModelFormMixin adding the class ng-init if the django form is bound. 

thanks you very much.

**Comment by jrief** [comment]
Using ``ng-init`` is deprecated by the AngularJS team. I always try to avoid it as much as possible.

BTW. django-angular is shipped with special directives which can handle bound (in Django terms) forms. This directive then handles the initialization.

**Comment by Bgeninatti** [comment]
jrief. Thanks you for your response. I will try this.

regards
