### ISSUE TITLE
Docs about reverse url and django-angular version

### ISSUE THREAD

**Issue by adrienbrunet** [jrief/django-angular#202]
The docs refers to django-angular version prior to 0.8 and from 0.8. It needs to be updated but I'm not sure from which version the url management changed. See http://django-angular.readthedocs.org/en/latest/reverse-urls.html

**Comment by jkosir** [comment]
Not exactly sure what you're referring to, the documentation page is for 0.8+ version (middleware), with only a link to previous vesion?

**Comment by adrienbrunet** [comment]
I'm confused. Latest version of django-angular is 0.7.15. What are we talking about with this 0.8+? Am I missing something obvious? I have the feeling that 0.8+ refers to 0.7.15+ (?). I may have missed a branch with new features expected in django-angular 0.8+. (?) I feel the docs shouldn't be stating anything that is not actually available yet. :confused:

**Comment by jkosir** [comment]
Oh yeah, my bad. The latest version is 0.7.15, but the middleware urls reversing (that the docs refer to) is available in it. So it's just the version in documentation that's wrong. I guess I thought the new version will be released as 0.8 instead of 0.7.15 at the time.

I think it would make more sense to tag this update as 0.8, as the api for reversing urls did change (now needs middleware). @jrief what do you think?
Otherwise I'll just fix the version in docs to 0.7.15.

**Comment by adrienbrunet** [comment]
:+1:

**Comment by jrief** [comment]
For me its OK to bump to version 0.8.0.
If everything is ready, please give me a note and I will push it to PyPI.

**Comment by jkosir** [comment]
As far as I'm concerned it's all ready.

**Comment by adrienbrunet** [comment]
:+1:

**Comment by jrief** [comment]
This means that we are ready for 0.8?

Something else I then will do, is to to rename ``djangular`` to ``djng``. On Django Conf 2015 there was a complaint about naming ambiguity, see here: https://vimeo.com/channels/952478/135038677

BTW, nice talk from somebody who uses django-angular

**Comment by adrienbrunet** [comment]
Yep, was there, the talk was nice and the guy too =) ping @AncientSwordRage. (he already participated in the repo)

1st december, I have a django meetup in Paris, I'll try to present django-angular. I'll give you the presentation of course. Anyway, we're moving away from the initial subject. =)

**Comment by AncientSwordRage** [comment]
:+1:

**Comment by adrienbrunet** [comment]
@jrief are we going to launch 0.8? Django 1.9 is out, some changes are not included in 0.7.15 (like in the import). Right now, the version provided by Pip is not working with 1.9

**Comment by adrienbrunet** [comment]
We really should launch that 0.8 version now. 0.7.16 would have been nice with 2016 coming really soon now but who cares? Let's release some work to the wild. Closing this.
