### ISSUE TITLE
RMI not properly documented

### ISSUE THREAD

**Issue by RadoRado** [jrief/django-angular#207]
By reading the documentation - https://github.com/jrief/django-angular/blob/master/docs/remote-method-invocation.rst - it is not very clear how the RMI works?

Should something be added to the urls? There is no example.

If you follow the given code snippets, in the end, the `all_rmi` tag returns an empty object - `{}`.

So - should something be added to the urls in order for the RMI to work?

**Comment by Ivaylo-Bachvarov** [comment]
:+1:

**Comment by kdkocev** [comment]
:+1:

**Comment by adrienbrunet** [comment]
Thanks for reporting. We'll get on that soon.

**Comment by RadoRado** [comment]
We solved the problem.

The url for the view must have a `name` argument. I think this should be documented ;)

**Comment by adrienbrunet** [comment]
Yep I saw that on Issue #165 :+1:
