### ISSUE TITLE
Js files management

### ISSUE THREAD

**Issue by adrienbrunet** [jrief/django-angular#209]
Hi @jrief, the files in /djangular/static refers to django-angular v0.7.11 (in the comments)
See https://github.com/jrief/django-angular/blob/master/djangular/static/djangular/js/django-angular.js

Even if it's up to date, we should provide a way to generate these files each time a js file is updated and update the version as well. Either manually and each contributor will have to do it if they update a js file or automagically. Also in both case, we should add a "contribute" section in the docs t explain that..

What did you used so far to generate these files ?

Cheers

**Comment by jrief** [comment]
So far I used grunt, and there is a Gruntfile.js in folder ``client``.
Nowadays I'd use gulp, but this has to be written yet.
Also, I havn't found any nice way yet to start gulp/grunt from within a Python process without requiring a shell. Having to rely on a shell can be a major problem any non-Unix development system.
Any ideas?

**Comment by adrienbrunet** [comment]
Oh yeah you're absolutely right. I did not see the conf files. We need to add some more tools to sync our djangular.__version__ and the client package.json version but that's it.
