### ISSUE TITLE
request.environ['QUERY_STRING'] returned in unicode, not utf-8

### ISSUE THREAD

**Issue by metteludwig** [jrief/django-angular#213]
The middleware.py changes request.environ['QUERY_STRING'] from non-unicode to unicode. This makes non-ascii characters not being processed correctly by django.http.request.QueryDict.__init__.

Will create pull request shortly, would be glad to have it merged soon. (Messy requirements.txt-files with github-references are the worst.)

**Comment by jrief** [comment]
Closed via #216
