### ISSUE TITLE
Horizontal-form are not rendered correctly.

### ISSUE THREAD

**Issue by adrienbrunet** [jrief/django-angular#217]
To have a bootstrap horizontal form, we can add `class="form-horizontal"` to the `<form...>` html.
Then, in our form, we may add:

```
field_css_classes = {
    '*': 'form-group has-feedback col-md-12 col-xs-12',
}
label_css_classes = "control-label col-xm-2 col-md-2"
widget_css_classes = "col-md-10 col-xs-10"
```

If we try this with the demo application, we then have several problems:
- the "sex" radio inputs "male" and "female" are not well aligned.
- The previous field field uses a ChoiceField with a RadioSelect widget which does NOT come from djangular.forms.widgets /!!\, changing that does not solve the problem above as far as I know but what the point of the custom radioselect widget if we don't even need/use it in our example?
- "help-text" are miss aligned as well (on the left instead of below the input)

**Comment by jrief** [comment]
Please retry with the current version. The form shall be marked as Bootstrap3.
