### ISSUE TITLE
Is this ready for Django 1.9?

### ISSUE THREAD

**Issue by jamshi** [jrief/django-angular#222]
Is the version 0.7.16 available in python package.

**Comment by jrief** [comment]
No, not yet. A few tests are still pending, but of course, you may use it at your own risk.

**Comment by jrief** [comment]
@jamshi sorry, you asked two questions: 0.7.17 in not yet ready on PyPI, but django-angular is ready for Django 1.9.

**Comment by jamshi** [comment]
can i install for django1.9 from PyPI

**Comment by adrienbrunet** [comment]
Hum, django-angular is compatible with django 1.6+.
Django 1.9 is supported from 0.7.16 which is available on github only for now. The official release on PyPi will be available soon..
