### ISSUE TITLE
Rebuilding request in middleware

### ISSUE THREAD

**Issue by ka7eh** [jrief/django-angular#227]
I'm using django-angular (latest version from github) with django1.9 and ran into a problem with the middleware.
When the request is rebuilt in middleware, its `path` property gets updated, but `path_info` property stays the same, i.e. `/angular/reverse/`, which causes Django to throw Http404 error in `django.core.handlers.base` at `resolver_match = resolver.resolve(request.path_info)`.
I remember using django-angular with older versions of django without having any problem, so I'm not sure what's changed. For now I've managed to fix this problem by updating the request (see https://github.com/ka7eh/django-angular/commit/d237becedd82f0067e1b044db29c356bad7315d1), but thought to check and see if anyone has any idea about this issue.

**Comment by jkosir** [comment]
Um yeah I've done some updates to the request building code lately. I'll use your fix and check if there's anything else to add soon.

**Comment by jkosir** [comment]
Also added resolved url into ``path_info`` and some additional tests.

**Comment by ka7eh** [comment]
Cool! :)
