### ISSUE TITLE
Serializing @property methods in CRUD view

### ISSUE THREAD

**Issue by jorenham** [jrief/django-angular#229]
I would like to add an `@property` method to the `fields` of a `NgCRUDView`, but this is not supported at the moment.

**Example:**

```python
class Person(models.Model):
    first_name = CharField(max_length=100)
    last_name = CharField(max_length=100)

    @property
    def full_name(self):
        return '%s %s' % (self.first_name, self.last_name)

class PersonView(NgCRUDView):
    model = Person
    fields = ('full_name')
```

How should I proceed?

**Comment by jrief** [comment]
I haven't tested this, but probably you need a setter decorator, say:

```
    @full_name.setter
    def full_name(self, combined_name):
        self.first_name = ... do some regex magic on combined_name
        self.last_name = ... more regex magic
```

**Comment by adrienbrunet** [comment]
If you absolutely want to stick to NgCRUDView (which I discourage, see my second point), you can define a custom serializer for your NgCRUDView and add your properties in it.

If you're starting to use django-angular more and more, NGCrudView are great to begin with but you should consider using some more battle-proof library to handle your CRUD views such as django-rest-framework. Such support is then included =)

Let me know if you need more help.

**Comment by jorenham** [comment]
Thank you for your assistance. I'm going for the [custom serializer](http://stackoverflow.com/a/30215745/1627479) option.
