### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by fjbardelli** [jrief/django-angular#233]
It is possible to make the translation of messages to other idiema valicion, as is Spanish.

**Thank execelte work.**

**Comment by fjbardelli** [comment]
When the form is assembled in django the fields are one below the other, but I have a form where the fields are small, and I need them next to each other, one on the right and left ortro the same row of formuario .

 What would be the correct way to customize the spectrum of the echos fromularios with this library.


 **Thank execelte work.**

**Comment by adrienbrunet** [comment]
Please open a different issue for the horizontal form. lus,there is already an existing issue opened about that. Thanks =)

**Comment by adrienbrunet** [comment]
About the translation, I don't know if it's in our scope right now but feel free to provide a spanish translation. @jrief @jkosir What's the plan about that?

**Comment by jkosir** [comment]
Um I don't really know the form validation code much, but doesn't it use django-generated error messages? So if you have django locale set to spanish they should be in spanish?

**Comment by jrief** [comment]
Just had a look at the code, yes we do have a few (3) translations string. I already added German.

I now added I18N support to the projects. If someone wants to add it to transiflex, please do so.

@fjbardelli 
In the meantime, please use

```
cd django-angular/djangular
django-admin.py makemessages --locale=en
```

then edit file ``locale/en/LC_MESSAGES/django.po``, commit it and create a pull request.

Sorry for not answering earlier.

**Comment by adrienbrunet** [comment]
Great ! We should add this in a contribute file for further translations.

**Comment by adrienbrunet** [comment]
PR #235 has fr and es translations if you'd like to review it. Poke @fjbardelli

**Comment by adrienbrunet** [comment]
PR #236 adds a contributing.md file to the repo. Mainly based on the django contributing file with translation guidelines.
