### ISSUE TITLE
Clarification for documentation on how to use partials

### ISSUE THREAD

**Issue by TravisDart** [jrief/django-angular#237]
[The docs](http://django-angular.readthedocs.org/en/latest/integration.html#partials) contain the following paragraph about including partials:

    In AngularJS, when used together with external templates, static HTML code often is loaded by a
    `$templateCache`_. These so named partials can be placed in their own sub-directory below
    ``STATIC_ROOT``.

I don't really understand this paragraph. Right now, I'm hardcoding the static URL path to the partials, but it sounds like there's a better way using `$templateCache`.

* What is the significance of the underscore after `$templateCache`?
* What are the "so named partials"? Is this a special subdirectory in `STATIC_ROOT`?

Can you shed some light on this subject?

**Comment by jrief** [comment]
sorry, I forgot to add the reference link.
should be fixed now.
I think the AngularJS docs are much better and explain this in detail.
