### ISSUE TITLE
[InvalidTemplateLibrary]; cannot import name 'import_by_path'

### ISSUE THREAD

**Issue by saintcrawler** [jrief/django-angular#238]
Trying to install this app into clean project. Pip-installed, then added '`djangular`' to the `INSTALLED_APPS`. But when i try to load very simple view, i've got this error: `Invalid template library specified. ImportError raised when trying to load 'djangular.templatetags.djangular_tags': cannot import name 'import_by_path'`. Here's my view: 
```
def intro(request):
    return render(request, 'mf/index.html', {'greetings': 'hi there!'})
```
And index.html:
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Minefields</title>
</head>
<body>

  <h1>{{ greetings }}</h1>

</body>
</html>
```

Am i dumb and forgot to add something, or is it a real error? Btw, when i tried JsonResponse first, it was fine.

P.S. virtualenv packages (using python 3.5):
```
Django==1.9.2
django-angular==0.7.15
wheel==0.24.0
```

**Comment by jrief** [comment]
In Django 1.9 this has been renamed to ``import_string``.
This has been fixed in the current Github version, which will be released soon.

**Comment by saintcrawler** [comment]
OK. Thank you!
