### ISSUE TITLE
Fixed a bug in NgModelFormMixin.get_form_data()

### ISSUE THREAD

**Issue by jrief** [jrief/django-angular#247]
Using ``and ... or ...`` as ternary operator can have unwanted side effects when working with booleans.
I therefore changed those occurrences to ``... if ... else ...``.
The patch is already committed, and this issue is only for information.
Will be released with 0.8.1

**Comment by adrienbrunet** [comment]
Yep, way better that way. And it's more readable!

**Comment by jrief** [comment]
Fixed in 0.8.1
