### ISSUE TITLE
[$injector:unpr] Unknown provider: djangoRMIProvider

### ISSUE THREAD

**Issue by Luancem** [jrief/django-angular#252]
hello,
I'm coverting my project from Django&jQuery to Angular&Django. But I encountered an issue. could you help me? Thank you.

Copied my code here:
**url.py**
_from django.views.generic import TemplateView
url(r'^navigation', TemplateView.as_view(template_name='navigation.html')),_
**views.py**
_class MyJsonView(JSONResponseMixin, View):
    template_name = "navigation.html"  
    @allow_remote_invocation 
    def navigation(self):
        data={"name":"Luancem"}
        return data_
**controller.js(implenmented the controller TreeController defined in html)**
_(function (ng) {
    var app = ng.module('tree', ['tree.directives']);
    var tags = '{% djng_all_rmi %}';
    app.config(function (djangoRMIProvider) {
        djangoRMIProvider.configure(tags);
    });
    app.controller("TreeController", function ($scope, djangoRMI) {
    ... ...
    })(angular);_

Follow the user guide, I am not sure where should {% load djng_tags %} write in html or controller.js?
When I write it in html, it reports [$injector:unpr] Unknown provider: djangoRMIProvider

**Comment by adrienbrunet** [comment]
Hi, there is a dedicated tag on stackoverflow for that kind of question. This does not relate directly with the implementation of this library, does it? I feel you're missing the injection dependency `'djng.rmi'`

Please refer to the docs to see how modules are injected. (see the `{% ng_module_dependencies %}` tag.

Feel free to reopen the issue if you find something wrong in our library.
Happy to know django-angular can help you somehow. Cheers.

**Comment by elongq** [comment]
Hi adrienbrunet,
Sorry to still ask you some basic questions.
Our code is as below, but there is an error indicate that the djangoRMI is null. 
Very appreciated if you can help.
    <script src="/static/js/angular.js"></script>  
    <script src="/static/js/django-angular.min.js" type="text/javascript"></script>   
    <script src="/static/js/TreeDirectives/TreeDirectives.js"></script>
    {% load djng_tags %}
    <script type="text/javascript">
    var app = angular.module('tree', ['tree.directives', 'djng.rmi']);
    var tags = {% djng_current_rmi %};
    app.config(function(djangoRMIProvider) {
        djangoRMIProvider.configure(tags);
        console.log(djangoRMIProvider);
    });
    app.controller("TreeController", function ($scope, djangoRMI) {
        var tc = this;
        $scope.invoke = function() {
          //alert("entering invoke");
          djangoRMI.navigation().success(function (data){
            tc.tree = data;
            alert(tc.tree);
          }).error(function(data){
            alert("error");
              });
        };
    })
  </script>

Error: djangoRMI is null
$scope.invoke@http://135.252.225.6:8995/navigation.html:33:11
anonymous/fn@http://135.252.225.6:8995/static/js/angular.js line 14086 > Function:2:206
expensiveCheckFn@http://135.252.225.6:8995/static/js/angular.js:15076:18
ngEventHandler/</callback@http://135.252.225.6:8995/static/js/angular.js:24546:17
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://135.252.225.6:8995/static/js/angular.js:16820:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://135.252.225.6:8995/static/js/angular.js:16920:20
ngEventHandler/<@http://135.252.225.6:8995/static/js/angular.js:24551:17
n.event.dispatch@http://135.252.225.6:8995/static/js/jquery-2.2.0.min.js:3:7467

**Comment by Sylvus** [comment]
I know this is old but you need something like

```
        {% block ng_module_definition %}
		var my_app = angular.module('djangular-demo', {% block ng_module_dependencies %}['djng.rmi']{% endblock ng_module_dependencies %}).config(function($httpProvider) {
            $httpProvider.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
        });
	    {% endblock %}
```

Also don't forget to include the js library. 
`<script src="{% static 'djng/js/django-angular.js' %}" type="text/javascript"></script>`

And regarding documentation, I think you should update it and explain these things (I had to figure them out by myself).

**Comment by jrief** [comment]
Not a real bug, but documentation is missing.

**Comment by Sylvus** [comment]
I finally figured it out. Regarding the djangoRMI is null Error:
Make sure you to load the tags and set them:
```
    var tags = {% djng_current_rmi %};
    my_app.config(function(djangoRMIProvider) {
        djangoRMIProvider.configure(tags);
    });
```

The problem is djng_current_rmi might return null. This happens when the context does not provide a view variable. This in turn happens when you specify your class view like this:
`class MyJSONView(JSONResponseMixin, View)`
instead of using this:
`class MyJSONView(JSONResponseMixin, ContextMixin, View)`

So the documentation is not only poor but also wrong! Please update it, this took me over an hour to figure out.

**Comment by davidzwa** [comment]
Still lacking documentation! This is very hard to work with, and it's 2 years later!
