### ISSUE TITLE
Question: wouldn't .ajax(request) be better as middleware or view mixin?

### ISSUE THREAD

**Issue by racitup** [jrief/django-angular#269]
I've been scratching my head for hours trying to figure out why my ajax json data submitted by a djng form to my native django CBV doesn't appear in the request.POST dict.
It turns out I had not scrolled down far enough in the [example](http://django-angular.awesto.com/model_scope/) to see the `.ajax()` method :-(

In any case having found [this](https://coderwall.com/p/mwhmfg/posting-from-angular-to-django) article, wouldn't this be better as a middleware like `AngularUrlMiddleware`?

Frankly I think it's an oversight that django provides an is_ajax method, but doesn't decode json request.body content into the POST dict or mention anything about it [here](https://docs.djangoproject.com/en/1.10/topics/class-based-views/generic-editing/#ajax-example).

**Comment by jrief** [comment]
But nowadays, native JSON is much more convenient and REST interfaces use it both ways. In my opinion, the QueryDict is a fossil from an epoch, when browsers communicated with multipart/form-data. django-shop and django-angular always use native JSON when communication through ajax, and I strongly believe that this will become the standard in the future. Therefore I strongly oppose the introduction of such a middleware.
