### ISSUE TITLE
Add suport for bootstrap4

### ISSUE THREAD

**Issue by elcone** [jrief/django-angular#272]
Or add documentation on how to create custom html

**Comment by adrienbrunet** [comment]
I'm almost done adding bootstrap4 support. More coming soon =)

**Comment by elcone** [comment]
that's great @adrienbrunet thank's!

**Comment by adrienbrunet** [comment]
I've added a branch with bootstrap4 support called bootstrap4. I haven't battle tested it yet. Please have a look and give me feedback if something is missing or not implemented correctly. Feel free to edit the files yourself and make a pull request ;)

I've done it between two Christmas meals, it may be of poor quality.. :santa:

Cheers (closing this, please go on the PR thread now, see  PR #274 )
