### ISSUE TITLE
Django 1.10 support via our tox

### ISSUE THREAD

**Issue by adrienbrunet** [jrief/django-angular#279]
It seems django-angular works more or less with Django 1.10 (I haven't really tested it entirely).

However, if we have django 1.10 in our tox config, we have a huge load of failing tests.

We could drop support for django 1.7 and  fully support django1.10, it should be easier to be 1.11 compatible next year. =)

**Comment by jrief** [comment]
Yes, dropping support for 1.7 is a good idea.
In my projects, I use django-angular with django-1.10 without any problems.

**Comment by adrienbrunet** [comment]
Done. See #281
