### ISSUE TITLE
Django 1.11 removes ChoiceFieldRenderer class

### ISSUE THREAD

**Issue by msaysell** [jrief/django-angular#284]
With the new [template based rendering](https://docs.djangoproject.com/en/dev/releases/1.11/) of django 1.11, the choice field renderer class has been removed ([source](https://docs.djangoproject.com/en/dev/releases/1.11/#changes-due-to-the-introduction-of-template-based-widget-rendering)).

This stops projects using django angular from even running the development server since [it is used to add ng-form to choice fields](https://github.com/jrief/django-angular/blob/master/djng/forms/widgets.py#L44)

**Comment by adrienbrunet** [comment]
Hey, thanks for your report.
We'll add support for django 1.11 very soon but please note that 1.11 is not even released yet. Unless you want to provide a patch, it may not be done right away. Cheers

**Comment by jrief** [comment]
Thanks for informing me

Seems to be a lot of work to replace this, grrrrr

**Comment by adrienbrunet** [comment]
Be brave jacob! \o/ :1st_place_medal:

**Comment by msaysell** [comment]
Oh thats ok, I wasn't expecting a quick fix I was just making you aware of the issue! Thanks for the quick reply! (I'd take a look at it myself but I'm not in a position to commit to this atm, sorry!)

**Comment by adrienbrunet** [comment]
https://www.djangoproject.com/weblog/2017/feb/20/django-111-beta-1-released/

We need to plan to rewrite some bits of code...

**Comment by mikicz** [comment]
Hi, how's this looking?

**Comment by adrienbrunet** [comment]
Well, looks like we lack some time to write it. Would you be interested in contributing? ;)

**Comment by mikicz** [comment]
Oh... Well I don't know your source code very much, I don't know if I would be able to fix it... And I also don't have much time to do it either :/

**Comment by adrienbrunet** [comment]
django-angular 1.0 now supports django 1.11. Hooray
