### ISSUE TITLE
no urls_by_namespace in djng.core.urlresolvers

### ISSUE THREAD

**Issue by monsieurTut** [jrief/django-angular#285]
The documentation about partials mentions:
```python
from djng.core.urlresolvers import urls_by_namespace

my_partials = urls_by_namespace('partials')
```
But there is no function urls_by_namespace in djng.core.urlresolvers (v.0.8.4).

**Comment by adrienbrunet** [comment]
Indeed this function has been deprecated in favor of a new approach, [see here](http://django-angular.readthedocs.io/en/latest/reverse-urls.html) to handle URLs with djng. You can see the deprecation warning in previous version : [See this commit](https://github.com/jrief/django-angular/commit/9f2d0748ca68cb7afe6ae858f3d8a5562d9c62c2)

Would you like to contribute to the project and correct this part of the documentation ? It would be appreciated !

**Comment by jrief** [comment]
I removed it from the documentation now.
