### ISSUE TITLE
CheckboxInputs with initial values ignore initial values.

### ISSUE THREAD

**Issue by Ivan0xFF** [jrief/django-angular#295]
I've been putting the 1.11 test version through its paces and noticed this issue. A model form with a checkbox input will not respect the model field's initial value. 

I tracked down the problem to line 135 in djng/forms/angular_base.py:
`context = super(self.__class__, self).get_context(name, value, attrs)`

Is there a good reason to call super there? It's skipping the CheckboxInput get_context method and only running the Input get_context method.

**Comment by jrief** [comment]
I'll check this.

**Comment by Ivan0xFF** [comment]
I had 100% reproduction on this when I submitted the ticket, but now it seems to be working. False alarm?
