### ISSUE TITLE
get_context method on custom Widget is never called

### ISSUE THREAD

**Issue by Ivan0xFF** [jrief/django-angular#297]
If you declare a custom Widget and override the get_context method to add additional attributes, the overridden method is never called, the parent class' get_context method gets called instead.

**Comment by adrienbrunet** [comment]
Well, @jrief, you could have a look at [this SO post](https://stackoverflow.com/questions/18208683/when-calling-super-in-a-derived-class-can-i-pass-in-self-class). `self.__class__` may not refer directly to the class itself but one of its children which can lead to strange behavior or inifinte loop.

Why not using `super(TupleErrorList, self)` ? Am I missing something ? Was it intended in the first place ?

**Comment by adrienbrunet** [comment]
@Ivan0xFF Jacob reviewed your PR with a similar comment (see above). Can you update your PR ?

**Comment by jrief** [comment]
your fix has been integrated in version 1.0.1 and released on PyPI.

Please review PR #303 which will become version 1.1
It has a much cleaner interface for form field inheritance.
