### ISSUE TITLE
Please keep tagging releases on GitHub

### ISSUE THREAD

**Issue by besser82** [jrief/django-angular#306]
You released some new versions in the last few weeks, but unfortunately they are not tagged in the GitHub repo.  I'm maintaining the rpm packages for Fedora from the tags in the repo, to be able to build (and package as user documentation) sphinx html docs in one run.  It would be really good, if you could keep the tags in git anlong with the releases on Pypi.

**Comment by jrief** [comment]
Thanks for the reminder.
I forgot to tag the latest 1.1 release. Just fixed that.

**Comment by besser82** [comment]
Well, I still cannot see any new tags since v1.0.0 in the github repo…  Maybe you forgot to `git push --tags`?

**Comment by jrief** [comment]
Sorry, I'm using Tower, which pushes tags automatically. For some reason that was deactivated.

**Comment by besser82** [comment]
Now it works, thank you!  =)
