### ISSUE TITLE
How to Start a fresh Project of django-angular

### ISSUE THREAD

**Issue by amitasthana** [jrief/django-angular#320]
I know its a kind of newbie question. However please help. 

How to Start a fresh Project of django-angular?

**Comment by adrienbrunet** [comment]
Documentation is a good place to start with ([here](http://django-angular.readthedocs.io/en/latest/installation.html)). Follow the installation part, and try to implement it for one form on your own.

You can, as you tried, have a first eye at the example repo and of course the result (also available [there](http://django-angular.awesto.com/classic_form/))
