### ISSUE TITLE
Please test upcoming version of django-angular 2.0

### ISSUE THREAD

**Issue by jrief** [jrief/django-angular#322]
Exciting news from the core maintainer of django-angular:
Version 2.0 is about of being released.

Please help me to review this pull request
https://github.com/jrief/django-angular/tree/releases/2.0.x
and have a look at the site explaining its features interactively:
https://django-angular.awesto.com/model_scope/

**Comment by adrienbrunet** [comment]
I think the documentation about "Running the demo" should mention `pip install -e .`.

Also, I think `pyquery` is missing from the example's requirements.

Then, there is 1 failing test and 2 warnings :

```
(djng) ~/projects/django-angular/examples:master ★  ./manage.py  test                                                                                                                                                            12:21:28
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.........................../home/adrien/projects/django-angular/djng/sekizai_processors.py:27: UserWarning: This postprocessor is deprecated. Read on how to resolve AngularJS dependencies using `{% with_data "ng-config" ... %}`
  warnings.warn("This postprocessor is deprecated. Read on how to resolve AngularJS dependencies using `{% with_data \"ng-config\" ... %}`")
./home/adrien/projects/django-angular/djng/sekizai_processors.py:20: UserWarning: This postprocessor is deprecated. Read on how to resolve AngularJS dependencies using `{% with_data "ng-requires" ... %}`
  warnings.warn("This postprocessor is deprecated. Read on how to resolve AngularJS dependencies using `{% with_data \"ng-requires\" ... %}`")
..............................E...........
======================================================================
ERROR: test_radio_field (server.tests.test_validation_forms.NgFormValidationMixinTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adrien/projects/django-angular/examples/server/tests/test_validation_forms.py", line 100, in test_radio_field
    self.assertEquals(label.text.strip(), "Female")
AttributeError: 'NoneType' object has no attribute 'text'

----------------------------------------------------------------------
Ran 70 tests in 0.993s

FAILED (errors=1)
Destroying test database for alias 'default'..
```

**Comment by adrienbrunet** [comment]
We could also add the step:

`npm install` in "Running the demo"

**Comment by jrief** [comment]
Thanks @adrienbrunet 
I'll check why we have a deviation here. On Travis everything seems to work.

**Comment by maltitco** [comment]
./manage.py test

Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.........................<html>
 <body>
  <ul class="djng-form-errors" ng-cloak="" ng-show="RW1haWxGb3Jt.$pristine">
   <li class="invalid" ng-bind="RW1haWxGb3Jt.$message" ng-show="RW1haWxGb3Jt.$error.rejected">
   </li>
  </ul>
  <ul class="djng-field-errors" ng-cloak="" ng-show="RW1haWxGb3Jt['email'].$pristine">
   <li class="invalid" ng-bind="RW1haWxGb3Jt['email'].$message" ng-show="RW1haWxGb3Jt['email'].$error.rejected">
   </li>
  </ul>
  <p>
   <label for="id_email">
    E-Mail
   </label>
   <input class="form-control" id="id_email" name="email" ng-foo="bar" ng-model="form_data['email']" required="" type="email"/>
  </p>
 </body>
</html>
../Users/malt/django-angular/djng/sekizai_processors.py:27: UserWarning: This postprocessor is deprecated. Read on how to resolve AngularJS dependencies using `{% with_data "ng-config" ... %}`
  warnings.warn("This postprocessor is deprecated. Read on how to resolve AngularJS dependencies using `{% with_data \"ng-config\" ... %}`")
./Users/malt/django-angular/djng/sekizai_processors.py:20: UserWarning: This postprocessor is deprecated. Read on how to resolve AngularJS dependencies using `{% with_data "ng-requires" ... %}`
  warnings.warn("This postprocessor is deprecated. Read on how to resolve AngularJS dependencies using `{% with_data \"ng-requires\" ... %}`")
..................<ul ng-show="U3Vic2NyaWJlRm9ybQ['email'].$dirty && !U3Vic2NyaWJlRm9ybQ['email'].$untouched" class="djng-form-control-feedback djng-field-errors" ng-cloak><li ng-show="U3Vic2NyaWJlRm9ybQ['email'].$error.required" class="invalid">This field is required.</li><li ng-show="U3Vic2NyaWJlRm9ybQ['email'].$error.email" class="invalid">Enter a valid email address.</li><li ng-show="U3Vic2NyaWJlRm9ybQ['email'].$valid" class="valid"></li></ul>
............E...........
======================================================================
ERROR: test_radio_field (server.tests.test_validation_forms.NgFormValidationMixinTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/malt/django-angular/examples/server/tests/test_validation_forms.py", line 98, in test_radio_field
    self.assertEquals(label.text.strip(), "Female")
AttributeError: 'NoneType' object has no attribute 'text'

----------------------------------------------------------------------
Ran 70 tests in 1.314s

FAILED (errors=1)
Destroying test database for alias 'default'...

**Comment by jrief** [comment]
OK. Changed the docs to invoke ``py.test`` or ``tox``.

So, @maltitco from your point of view everything is OK for releasing version 2.0?

**Comment by maltitco** [comment]
@jrief I found first issue 
![nagranie ekranu 2017-11-15 o 16 52 27](https://user-images.githubusercontent.com/1561204/32845898-3764ca38-ca26-11e7-8abf-ce17ccbbb52e.gif)

**Comment by maltitco** [comment]
second issue with Ajax button nothing happen.
![nagranie ekranu 2017-11-15 o 17 04 41](https://user-images.githubusercontent.com/1561204/32846364-59de0984-ca27-11e7-9066-bb6e45fb388c.gif)

**Comment by jrief** [comment]
The first issue is solved.

I presume that the second one, is not a real issue. Could you please retry locally and check if you see an error message above. Remember that the combination "John Doe" is rejected.
If that's the case, I agree however that it's not the best user experience. Then I have to rethink how to improve it.

@maltitco Thanks anyway and please retry.

**Comment by jrief** [comment]
@maltitco I have found a solution for the second problem, provided it is the problem I assumed.
Check the branch ``releases/2.0.x``

**Comment by maltitco** [comment]
@jrief in /model_scope/ form Submit via Ajax don't work:

![nagranie ekranu 2017-11-16 o 09 38 46](https://user-images.githubusercontent.com/1561204/32881737-75cd62ee-cab2-11e7-9165-b56812a48ee1.gif)

She same is in combined_validation in console TypeError: the JSON object must be str, not 'bytes'

2. File upload
 - you can do drag and drop other file than pdf.
 - after deleting files are not deleted from the folder
 - send button does nothing

![nagranie ekranu 2017-11-16 o 09 51 32](https://user-images.githubusercontent.com/1561204/32882439-a251b2c8-cab4-11e7-929b-518492bb0295.gif)

**Comment by jrief** [comment]
@maltitco About File upload
* D&D files other than PDF: This is an issue of https://angular-file-upload.appspot.com/ – unless I misunderstood their docs, I can't really prevent this.
* these files are uploaded into a temporary folder, which must be cleaned from time to time anyway.
* What do you mean with that? For me the Submit button works perfectly.

**Comment by maltitco** [comment]
On my local:
model_scope Submit via Ajax:

> File "/Users/malt/test/django-angular-46d159564f34da7f6c8b0c46e1f0176008864cfd/examples/server/views/model_scope.py", line 22, in ajax
    request_data = json.loads(request.body)
  File "/Users/malt/.pyenv/versions/3.5.4/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
[2017-11-16 12:46:45,878 basehttp] ERROR: "PUT /model_scope/ HTTP/1.1" 500 13806

When it comes to uploading files it was missing npm install ng-file-upload.
