### ISSUE TITLE
ChoiceFieldRenderer not available in Django 2.x

### ISSUE THREAD

**Issue by br0th3r** [jrief/django-angular#326]
File "./env/lib/python3.5/site-packages/djng/forms/widgets.py", line 44, in <module>
class ChoiceFieldRenderer(widgets.ChoiceFieldRenderer):
AttributeError: module 'django.forms.widgets' has no attribute 'ChoiceFieldRenderer'

Any solution?

**Comment by jrief** [comment]
I had no time yet to migrate django-angular to Django-2.0
You want to try?

**Comment by br0th3r** [comment]
My mistake using an olde version, it is not happenindg on the latest version.
