### ISSUE TITLE
Automatically generated form names broken in Python 3

### ISSUE THREAD

**Issue by WoLpH** [jrief/django-angular#333]
When Python 3 is used the automatically generated form name return a `b'.....'` type string which angular doesn't like.

My guess is that it's caused by this: https://github.com/jrief/django-angular/blob/7bd33dd8b48486be11d987611099bc8b74d068c0/djng/forms/angular_base.py#L301

There should a string cast/decode over there.

**Comment by WoLpH** [comment]
Excellent! Thanks for the quick fix @jrief :)

**Comment by jrief** [comment]
Thanks for reporting.
Please recheck with HEAD from master, if everything is OK, I'll release a new version.

**Comment by WoLpH** [comment]
I've just tested it, works without a problem now.

**Comment by jrief** [comment]
Version 2.0.3 is available from https://pypi.org/project/django-angular/
