### ISSUE TITLE
Trouble integrating into django-cookiecutter project

### ISSUE THREAD

**Issue by slandau3** [jrief/django-angular#334]
Hello, I'm trying to integration django-angular into my project that was made with [django-cookiecutter](https://github.com/pydanny/cookiecutter-django), but I'm not having much luck. I followed the documentation and I installed django-angular via pip and added the npm package in my static directory but when I attempt to add "djing" to the list of installed apps it tells me that the package doesn't exist. Likewise when I try to import djing.*, the module "djing" is not recognized.

**Comment by adrienbrunet** [comment]
Try with `djng`, no "i"

See http://django-angular.readthedocs.io/en/latest/installation.html#configuration

**Comment by slandau3** [comment]
wow I feel dumb.

**Comment by adrienbrunet** [comment]
No worries, enjoy ;)
