### ISSUE TITLE
angular.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module djangular-demo due to:

### ISSUE THREAD

**Issue by smeeteday** [jrief/django-angular#336]
It seems that djangular - demo can not be initialized. Please tell me how to deal with it.

Uncaught Error: [$injector:modulerr] Failed to instantiate module djangular-demo due to:
Error: [$injector:modulerr] Failed to instantiate module djng.forms due to:
Error: [$injector:unpr] Unknown provider: $parse
http://errors.angularjs.org/1.5.11/$injector/unpr?p0=%24parse
    at http://localhost:8000/static/node_modules/angular/angular.js:68:12
    at http://localhost:8000/static/node_modules/angular/angular.js:4563:19
    at getService (http://localhost:8000/static/node_modules/angular/angular.js:4716:32)
    at injectionArgs (http://localhost:8000/static/node_modules/angular/angular.js:4741:58)
    at Object.instantiate (http://localhost:8000/static/node_modules/angular/angular.js:4783:18)
    at provider (http://localhost:8000/static/node_modules/angular/angular.js:4599:36)
    at Object.provider (http://localhost:8000/static/node_modules/angular/angular.js:4591:16)
    at runInvokeQueue (http://localhost:8000/static/node_modules/angular/angular.js:4663:35)
    at http://localhost:8000/static/node_modules/angular/angular.js:4671:11
    at forEach (http://localhost:8000/static/node_modules/angular/angular.js:325:20)
http://errors.angularjs.org/1.5.11/$injector/modulerr?p0=djng.forms&p1=Error%3A%20%5B%24injector%3Aunpr%5D%20Unknown%20provider%3A%20%24parse%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Funpr%3Fp0%3D%2524parse%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8000%2Fstatic%2Fnode_modules%2Fangular%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8000%2Fstatic%2Fnode_modules%2Fangular%2Fangular.js%3A4563%3A19%0A%20%20%20%20at%20getService%20(http%3A%2F%2Flocalhost%3A8000%2Fstatic%2Fnode_modules%2Fangular%2Fangular.js%3A4716%3A32)%0A%20%20%20%20at%20injectionArgs%20(http%3A%2F%2Flocalhost%3A8000%2Fstatic%2Fnode_modules%2Fangular%2Fangular.js%3A4741%3A58)%0A%20%20%20%20at%20Object.instantiate%20(http%3A%2F%2Flocalhost%3A8000%2Fstatic%2Fnode_modules%2Fangular%2Fangular.js%3A4783%3A18)%0A%20%20%20%20at%20provider%20(http%3A%2F%2Flocalhost%3A8000%2Fstatic%2Fnode_modules%2Fangular%2Fangular.js%3A4599%3A36)%0A%20%20%20%20at%20Object.provider%20(http%3A%2F%2Flocalhost%3A8000%2Fstatic%2Fnode_modules%2Fangular%2Fangular.js%3A4591%3A16)%0A%20%20%20%20at%20runInvokeQueue%20(http%3A%2F%2Flocalhost%3A8000%2Fstatic%2Fnode_modules%2Fangular%2Fangular.js%3A4663%3A35)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8000%2Fstatic%2Fnode_modules%2Fangular%2Fangular.js%3A4671%3A11%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8000%2Fstatic%2Fnode_modules%2Fangular%2Fangular.js%3A325%3A20)
    at http://localhost:8000/static/node_modules/angular/angular.js:68:12
    at http://localhost:8000/static/node_modules/angular/angular.js:4692:15
    at forEach (http://localhost:8000/static/node_modules/angular/angular.js:325:20)
    at loadModules (http://localhost:8000/static/node_modules/angular/angular.js:4653:5)
    at http://localhost:8000/static/node_modules/angular/angular.js:4670:40
    at forEach (http://localhost:8000/static/node_modules/angular/angular.js:325:20)
    at loadModules (http://localhost:8000/static/node_modules/angular/angular.js:4653:5)
    at createInjector (http://localhost:8000/static/node_modules/angular/angular.js:4575:19)
    at doBootstrap (http://localhost:8000/static/node_modules/angular/angular.js:1809:20)
    at bootstrap (http://localhost:8000/static/node_modules/angular/angular.js:1830:12)
http://errors.angularjs.org/1.5.11/$injector/modulerr?p0=djangular-demo&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20djng.forms%20due%20to%3A%0AError%3A%20%5B%24injector%3Aunpr%5D%20Unknown%20provider%3A%20%24parse%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Funpr%3Fp0%3D%2524parse%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8000%2Fstatic%2Fnode_modules%2Fangular%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8000%2Fstatic%2Fnode_modules%2Fangular%2Fangular.js%3A4563%3A19%0A%20%20%20%20at%20getService%20(http%3A%2F%2Flocalhost%3A8000%2Fstatic%2Fnode_modules%2Fangular%2Fangular.js%3A4716%3A32)%0A%20%20%20%20at%20injectionArgs%20(http%3A%2F%2Flocalhost%3A8000%2Fstatic%2Fnode_modules%2Fangular%2Fangular.js%3A4741%3A58)%0A%20%20%20%20at%20Object.instantiate%20(http%3A%2F%2Flocalhost%3A8000%2Fstatic%2Fnode_modules%2Fangular%2Fangular.js%3A4783%3A18)%0A%20%20%20%20at%20provider%20(http%3A%2F%2Flocalhost%3A8000%2Fstatic%2Fnode_modules%2Fangular%2Fangular.js%3A4599%3A36)%0A%20%20%20%20at%20Object.provider%20(http%3A%2F%2Flocalhost%3A8000%2Fstatic%2Fnode_modules%2Fangular%2Fangular.js%3A4591%3A16)%0A%20%20%20%20at%20runInvokeQueue%20(http%3A%2F%2Flocalhost%3A8000%2Fstatic%2Fnode_modules%2Fangular%2Fangular.js%3A4663%3A35)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A8000%2Fstatic%2Fnode_modules%2Fangular%2Fangular.js%3A4671%3A11%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A8000%2Fstatic%2Fnode_modules%2Fangular%2Fangular.js%3A325%3A20)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fmodulerr

**Comment by jrief** [comment]
sorry, this was work in progress and I screwed something up.

**Comment by smeeteday** [comment]
Thank you. I am glad if I can help you something, but I am looking forward to it.
