### ISSUE TITLE
Survey about naming conventions - please participate!

### ISSUE THREAD

**Issue by jrief** [jrief/django-angular#35]
I noticed, that the current naming conventions are not very consistent.

Django-Angular's Javascript code, Directives start with ``djng-...``, which is in my opinion is a good choice.

Django-Angular modules start with ``ng.django.``... ,  which is distracting. In my opinion, a better prefix would be to also use ``djng.``...

Django-Angular Providers start with ``django``, for instance ``djangoForm``, ``djangoRMI`` and ``djangoWebsocket``. This in my opinion is somehow acceptable, since they already are part of a Django-Angular namespace.

In Django-Angular's Python code, Mixins are Prefixed with ``Ng...``. For consistency, shouldn't they rather be renamed to say ``DjNg...`` or ``djng``?

Please participate and point my on conventions used in similar third party modules.

**Comment by AncientSwordRage** [comment]
Anything but djangular...

**Comment by micgeronimo** [comment]
vote up for django_angular

**Comment by jrief** [comment]
I don't like to repeat the lemma "django" as part of a library name, because its too redundant.

My preference for now is ``djng`` because that makes sense in Django includes, as well as in Angular injections.

@AncientSwordRage I agree, using ``djangular`` was a bad decision. Sorry for that.

Other proposal:

What do you think about moving members from Form mixins, such as ``scope_prefix`` into the Form's Meta class?

**Comment by merwok** [comment]
IME the bad thing is when the importable name is much too generic, i.e. a django-comments PyPI package that installs a comments Python package.  Avoiding these import-name conflicts is important.  For the PyPI names, we have PyPI to avoid conflicts.  I don’t think naming a package that adds tags to Django projects “django-tags” is redundant: to the contrary, it says clearly what it does.  Naming extensions “pyramid_thing” is also a standard habit in the Pyramid community (which comes from the Zope community, where best practices for packaging have a long tradition).

**Comment by AncientSwordRage** [comment]
Please vote here:

https://www.opavote.org/vote/4962998909140992

**Comment by jrief** [comment]
@AncientSwordRage thanks for setting up the ballot.

**Comment by adrienbrunet** [comment]
Vote is closed. Name has been chosen and must change when releasing version 0.8 right @jrief ? Closing this

**Comment by jrief** [comment]
Yes, it will be changed for 0.8. Then in JS and Python we will use ``djng``?

**Comment by adrienbrunet** [comment]
yep ! :+1:

**Comment by NancyZY** [comment]
As a newer for Angular, I want to know why the "app.js" does not show in the Demo? What should I do for Angular file struct with django architecture? Thanks for your patience in advance

**Comment by AncientSwordRage** [comment]
@nancyZY it might be better to ask this add a new issue here,  or  as a question in stackoverflow.  They even have a djangular tag.

**Comment by adrienbrunet** [comment]
Please open a new issue for that. It is not related to the original post...
And your problem is not quite clear for me.

Have a look at `base.html` in the [templates folder](https://github.com/jrief/django-angular/blob/master/examples/server/templates/) :

	<script type="text/javascript">
	{% block ng_module_definition %}
		var my_app = angular.module('djangular-demo', {% block ng_module_dependencies %}[]
     {% endblock ng_module_dependencies %});
	{% endblock %}
    </script>

We define here the module 'djangular-demo'. It's the base of our angular app as you could find in any app.js file in some demo angularjs apps. Then for each different example, we add more specific code :

	{% block demo_scripts %}
	<script src="{{ STATIC_URL }}js/djng-tutorial.js" type="text/javascript"></script>
	{% endblock %}


Maybe try stackoverflow first if the question is more related to angularjs than directly this library. Thanks.

**Comment by jrief** [comment]
In 0.8.0 ``djangular`` has been renamed to ``djng``.
