### ISSUE TITLE
CheckboxChoiceInput breaks compatibility with django 1.5

### ISSUE THREAD

**Issue by AgDude** [jrief/django-angular#57]
The CheckboxChoiceInput class is not present in django 1.5.

https://github.com/django/django/blob/1.5.8/django/forms/widgets.py

This is the changeset where it was implemented:
https://github.com/django/django/commit/9ac4dbd7b53d187ca54f28e247d3a120660938ca

**Comment by adrienbrunet** [comment]
@AgDude It's been a while this ticket is opened but it's pointless if it is solved. I'm closing it now, if you still have some troubles, feel free to reopen it or another one.
