### ISSUE TITLE
Add "placeholder" to input fields

### ISSUE THREAD

**Issue by jrief** [jrief/django-angular#66]
Add a flag to djangular/styling/bootstrap3/forms.py which enables to render 

```
placeholder="<label>"
```

in input fields.

**Comment by adrienbrunet** [comment]
I'm not sure to understand what you want to do. Right now, if we add `self.fields['my_field'].widget.attrs['placeholder'] = 'foo bar'`, this works. Could you be more precise? Or close the issue if there's none.

**Comment by PrehistoricTeam** [comment]
I like this change, currently in all my projects I have a mixin:
```python
class PlaceholderFormMixin(object):
    def get_widget_attrs(self, bound_field):
        d = super(PlaceholderFormMixin, self).get_widget_attrs(bound_field)
        d["placeholder"] = bound_field.label
        return d
```
I find that setting the placeholder as the input label is pretty common on the web, so this could be a nice convenience.

**Comment by adrienbrunet** [comment]
Would you like to submit a PR? :pray: =)

**Comment by adrienbrunet** [comment]
@jrief See my branch "labelAsPlaceholders" (which depends on "bootstrap4")

**Comment by jrief** [comment]
please reopen, if this is still an issue.
With Django-1.11 lots of things changed.
