### ISSUE TITLE
SELECT widget sets data to undefined, even though ng-model contained data already

### ISSUE THREAD

**Issue by stuaxo** [jrief/django-angular#68]
I've got a choicefield with ng-model="group.selectedMessage.fields.sponsor". 

That ng-model has a value of "AA", which is one of the options in the SELECT.

On loading, the model gets set back to undefined.

As a test, I tried changing the widget to a TextInput, if i did this then it didn't reset the value.    Something about the SELECT is resetting the value.

**Comment by adrienbrunet** [comment]
I found the problem ! I ran into a similar issue and solve it. What happens is: your object (serialized) has a *number* as a foreignkey which represent the id of your model. But for a select, the expected values is a *string*. Details in PR #231

**Comment by adrienbrunet** [comment]
Even if the PR #231  fixes this particular problem, I think this issue also emphasize the need for an "Update Example" as requested in Issue #184

**Comment by stuaxo** [comment]
It sounds like SELECT should also use a number for consistency ?

Possibly, there should be some kind of error if tying to use a string with a numeric field ?

**Comment by adrienbrunet** [comment]
Well, we don't really have the choice. Select are using string as value. From [Angular doc](https://docs.angularjs.org/api/ng/directive/select):

> Note that the value of a select directive used without ngOptions is always a string. When the model needs to be bound to a non-string value, you must either explicitly convert it using a directive (see example below) or use ngOptions to specify the set of options. This is because an option element can only be bound to string values at present.

Moreover, if you try to set this value with a non string, this s what happens (still from [Angular doc](https://docs.angularjs.org/api/ng/directive/select)):

> If the viewValue of ngModel does not match any of the options, then the control will automatically add an "unknown" option, which it then removes when the mismatch is resolved.


For integerField, if you try to enter a string, you'll get an error. We've done what we can on our side for that I think (except the remaining bug, see opened issues). Unless you can think of a better way to handle this problem, I think it does the job.

Cheers (and thanks for responding so quickly, it took me 1year and a half to address your problem :frowning: )

**Comment by stuaxo** [comment]
Ah, good info.    I haven't been using Angular or Django for over a year, but most probably will again soon.

**Comment by adrienbrunet** [comment]
Hi again, in fact, I was wrong, it's a bit more complicated than that.
If you're _not_ using ng-options, then my hack is working. But if you're using it, it's plain wrong. (At least with angular 1.4). Indeed, they updated the ng-options directive and things get a bit more tricky.

- When not using ng-option, you need to ensure the data you're passing for the select match the expected values e.g. if it's a foreignkey, you have` <option value="114">` for example, you need to ensure the data you're passing is `"114"` and not `114` (string vs number)
- If you're using ng-option, the best solution is to use ng-options="myobject.attr_for_label for myobject in myobjects track by myobject.pk" and pass ayour foreignkey as an object.

@jrief I'm gonna revert my last pull requests. I thought it was working as expected, it's not.

**Comment by adrienbrunet** [comment]
I reverted my PR. One probem still subsist, If you bind with angular your form with one instance of an object with a foreignkey, the select may not be initialized correctly. (using ng-options usually get it working). When using ng-options, I don't have any problems. If you feel like you can improve it, feel free to reopen the issue it but it's been more than a year without activity on it, so I guess the case is closed.
