### ISSUE TITLE
Angular number validation broken

### ISSUE THREAD

**Issue by dangerski** [jrief/django-angular#69]
For number fields there is no error message for `field.$error.number`.  You can see this problem in the demo if you input non-number characters into a number field.  Instead of displaying a message about being an invalid number it says "This field is required".  If you have a number field that is **not** required, it will display **no** error message(but still highlights the field in red).

**Comment by adrienbrunet** [comment]
(Since I migrate from 0.7.10 to 0.7.13, I expected that would be fixed. But we still get "this field is required" even if a value is provided. I think if a user enters a string instead of a number, we should only display the message "Enter a number" or "Enter a whole number")

**Comment by adrienbrunet** [comment]
What a great night, I planned to fix it once for all... But it's already fixed (it's been a while I haven't tested if that particular problem was still there) :+1:
