### ISSUE TITLE
Form doesn't become valid when Django fails with a Validation error on some "custom" field

### ISSUE THREAD

**Issue by br0th3r** [jrief/django-angular#87]
When Django returns a validation error on some field, the rendered website doesn't set valid the form once the invalid field is filled with valid information.

Example:

I fill a DateField with a string and Djangular (by default) will not do any validation on the angular side, so I send the form and the result from Django is visible saying that I should fill the field with a valid date, then if I remove everything from the field or I fill it with a valid date, the form stays invalid anyway.

Some idea where the problem could be located?

Thank you,

PS: I know I can set specific validation for this DateField, but the validation some times can be related to the server side and in this cases the validation must happens on the server (not on the client), so I am looking forward to find a solution for the problem...not a work arround for the example I am giving with the DateField.

**Comment by rogueleaderr** [comment]
I just ran into a very similar issue (I'm not sure if it's the exact same one)

I had forms declared as:

    class HerdInfoInputForm(NgFormValidationMixin, Bootstrap3FormMixin, NgModelForm):

and everything appeared to work fine, until I submitted a form that passed client validation but not server validation. When that happened, typing a new value in the invalid field would not make the error go away nor mark the field as valid.

I figured out that that I could fix it by declaring my forms as:
    
    class HerdInfoInputForm(NgModelFormMixin, NgFormValidationMixin, Bootstrap3FormMixin, NgModelForm):

...instead. I must not have read the documentation closely enough but I assumed that NgModelFormMixin was intended to provide the same functionality as NgModelForm to classes that couldn't inherit directly from NgModelForm. Perhaps it would to someone more prominently point out that one sometimes needs both NgModelFormMixin and NgModelForm on the same class.

**Comment by jrief** [comment]
Ok. If so many users ran into that problem, I'll add a note to the documentation. The intention of this strict separation is to add ``ng-model`` attributes to Django Forms (using ``NgModelFormMixin ``) allowing to send that data back to the server via ``$http.post(...)`` and send back validated or erroneous Form data from the server to the client (using ``NgFormValidationMixin ``).

I hoped the the examples in the demo explained this in detail.
