### ISSUE TITLE
New demo page

### ISSUE THREAD

**Issue by jrief** [jrief/django-angular#94]
Today I launched a new demo page: http://djangular.aws.awesto.com/
Would be great, to get some feedback.
Jacob

**Comment by fcracker79** [comment]
That is a great job!
I am evaluating its adoption for my project. If I can achieve all the tasks I have, I will publish that adoption.

**Comment by jrief** [comment]
Sorry, I forgot to mention in this issue that I moved the demo from AWS to another provider. It now is located at http://django-angular.awesto.com/
